# General configuration
timezone: "America/Denver"
pve_cluster_name: "homelab"

# Packages to install on all nodes
common_packages:
  - vim
  - htop
  - curl
  - git
  - net-tools

# Repositories
pve_enterprise_repo: false
pve_no_subscription_repo: true

# Firewall
firewall_allow_ssh: true
firewall_allow_webui: true
firewall_allow_cluster: true
