all:
  children:
    pve:
      hosts:
        pve-srv-1:
          ansible_host: 10.10.10.1
          ansible_user: root
        pve-srv-2:
          ansible_host: 10.10.10.2
          ansible_user: root
        pve-srv-3:
          ansible_host: 10.10.10.3
          ansible_user: root
        pve-srv-4:
          ansible_host: 10.10.10.4
          ansible_user: root
