all:
  children:
    managers:
      hosts:
        manager1:
          ansible_host: 10.10.20.1
        manager2:
          ansible_host: 10.10.20.2
        manager3:
          ansible_host: 10.10.20.3
    workers:
      hosts:
        worker1:
          ansible_host: 10.10.20.11
        worker2:
          ansible_host: 10.10.20.12
